---
- name: setup samba
  hosts: samba
  become: true
  tasks:
    - name: create directory
      file:
        path: /home/ubuntu/share01
        state: directory
        mode: '2770'

    - name: samba install
      ansible.builtin.apt:
        name: samba
        update_cache: true
        state: latest
    
    - name: change permissions of share01 directory
      file:
        path: /home/ubuntu/share01
        owner: "ubuntu"
        group: "sambashare"

    - name: set smbpasswd
      shell: "printf 'ubuntu\nubuntu\n' | smbpasswd -a ubuntu"

    - name: adding lines to smb.conf
      ansible.builtin.blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [share01]
          comment = Samba share directory
          path = /home/ubuntu/share01
          read only = no
          writable = yes
          browseable = yes
          guest ok = no
          valid users = @ubuntu

    - name: enable smbd service
      command: systemctl enable --now smbd
